added a functioning example of jsdoc
jzjones/algo-util pull request #1
Opened 2022-04-01 16:52 UTC by TonyIommiSG

2022-04-04 15:47 UTC, jzjones requested changes

2022-04-04 15:47 UTC, jzjones commented on package.json
> +    "jsdoc": "^3.6.10",
should this be dev dependency?

2022-04-06 03:34 UTC, TonyIommiSG commented on package.json
> +    "jsdoc": "^3.6.10",
I guess I'm not sure when you would want dev vs non dev? From what I've read it depends and that some said for building libraries and such, that dev d's are for testing, local, etc. I feel this is not for testing but a feature of the library and would go in dependency, but I could be completely wrong haha.

2022-04-06 03:39 UTC, TonyIommiSG commented on src/abi.ts
> + * @returns {ABIContract
Updated. Is there any other details you think you'd want readers to have for now? Currently I continue with this, but can always add more later.

2022-04-06 15:06 UTC, jzjones commented on package.json
> +    "jsdoc": "^3.6.10",
I think a good way to think about it is if someone wants to use the package whats the minimal dependencies they need to get it to function

2022-04-07 21:19 UTC, closed without merging